FROM openjdk:8
WORKDIR /opt/mydocker/build
COPY . .
#设置时区
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
EXPOSE 8080
CMD java -jar hm-dianping-0.0.1-SNAPSHOT.jar
